// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyxojZCe4YPeS5QJvGJOl3RIPSdmZUnio',
    appId: '1:755600795713:web:06d1deec2f36cdccd0fec0',
    messagingSenderId: '755600795713',
    projectId: 'fluttersignin-57bda',
    authDomain: 'fluttersignin-57bda.firebaseapp.com',
    storageBucket: 'fluttersignin-57bda.appspot.com',
    measurementId: 'G-3F0T50CLHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUVVeOq2mBAFteQ5IKAymZT_l0F49Gt0',
    appId: '1:755600795713:android:a19148d8bdf9debdd0fec0',
    messagingSenderId: '755600795713',
    projectId: 'fluttersignin-57bda',
    storageBucket: 'fluttersignin-57bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_2FDdEqBGxn2DcOOw6Y6OJAov9dFHmI',
    appId: '1:755600795713:ios:b0aa0a10145c7924d0fec0',
    messagingSenderId: '755600795713',
    projectId: 'fluttersignin-57bda',
    storageBucket: 'fluttersignin-57bda.appspot.com',
    iosClientId: '755600795713-l5l39h3q6gjikhru91p50h69lb8a89om.apps.googleusercontent.com',
    iosBundleId: 'com.brainybeam.taskdemo.taskdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_2FDdEqBGxn2DcOOw6Y6OJAov9dFHmI',
    appId: '1:755600795713:ios:b0aa0a10145c7924d0fec0',
    messagingSenderId: '755600795713',
    projectId: 'fluttersignin-57bda',
    storageBucket: 'fluttersignin-57bda.appspot.com',
    iosClientId: '755600795713-l5l39h3q6gjikhru91p50h69lb8a89om.apps.googleusercontent.com',
    iosBundleId: 'com.brainybeam.taskdemo.taskdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyxojZCe4YPeS5QJvGJOl3RIPSdmZUnio',
    appId: '1:755600795713:web:bcb0556b31301d60d0fec0',
    messagingSenderId: '755600795713',
    projectId: 'fluttersignin-57bda',
    authDomain: 'fluttersignin-57bda.firebaseapp.com',
    storageBucket: 'fluttersignin-57bda.appspot.com',
    measurementId: 'G-9BDP36V9MG',
  );

}